### PR TITLE
Themable icon

### PR DESCRIPTION
**Pull request by elsiehupp**
Hi @MrCarroll~

I've added a GNOME/KDE-style icon and updated the references to it so that, ostensibly, the shell will be able to replace the icon with a themed alternative if a user is set up that way.

This [Stack Exchange answer](https://unix.stackexchange.com/a/602736) talks about how the shell parses `.desktop` files to find icons.

I say "ostensibly" because I really don't know my way around `snap`, and I haven't actually gotten the symbolic icon name to work on my system. So this should be considered more of a jumping-off point than a finished revision.

### CODE REVIEW

**Comment by JGCarroll** [comment]
Hello again!

I've taken a look into what snap can currently facilitate. Unfortunately it's rather opinionated on security matters even to the point icons have policies :P.

Changing the icon itself is fine, using your `.svg` works.

The name of the icon however is out of my control, the `.desktop` file isn't actually the same `.desktop` file that the system uses, Snap itself inspects and modifies it; for example it makes sure the `Exec=` line points to something inside the manifest and not say, `rm -rf ~`, and it does similar for `Icon=`. You can go into `/var/lib/snapd/desktop/` and look for yourself to see how it gets warped.

I'm reading it is possible to have generic/relative icon names, but snap will force it to have the form of `snap.joplin-james-carroll.joplin`, even if the package was named `joplin` without my name in it, it'd still need the form of `snap.joplin` or maybe `snap.joplin.joplin`. In the future it might be possible to make a proper human reviewed request to be able to just take `joplin` or `joplin-desktop`, but until then, this means you'd have to treat this (and every) snap as different from their native counterparts as far as the icons go. https://forum.snapcraft.io/t/proposal-support-the-icon-theme-spec-for-desktop-icons/10676

So I'm happy to take the .svg version as is, and if I can figure out how to get symbolic paths working I'll do that too so you and anyone else interested could change it locally without it being reset every update, but the current situation is it's just not technically possible to pick any arbitrary symbolic name and that's out my control entirely for the time being

**Comment by elsiehupp** [comment]
I mean, having the icon named `snap.joplin-james-carroll.joplin` is not the end of the world. I'm specifically trying to get the correct symbolic links set up with the [`mint-y-icons`](https://github.com/linuxmint/mint-y-icons/pull/280) theme, since [there's a user on the forum who uses it](https://discourse.joplinapp.org/t/alternative-macos-icon/8996/21). Basically it seems like the way icon themes handle name variations is with symbolic links within the icon theme itself, so having multiple name variations is not the end of the world.

Thanks for the explanation, by the way!

**Comment by JGCarroll** [comment]
If the exact name doesn't matter, I'll get back to you later when I can ensure the exact symbolic format I can change it to, I've asked for help on the Snapcraft forums and I'll dig around other peoples repos

**Comment by elsiehupp** [comment]
Cool. Once you know the exact name I can add it as a symbolic link for the `mint-y-icon` theme.

**Comment by JGCarroll** [comment]
So I've figured out what snap wants, and I can change the symbolic name to `snap.joplin-james-carroll.*`, in this case I'd prefer if the * was just "joplin", if in the future I can make a request for un-namespaced icons, I'd consider "joplin-desktop", but since the current system does make a distinction between the names in the `gui` folder and the new system is undocumented, I think it's cleaner this way for people who might look to this repository for examples on their own snaps.

If you can change the value to be `Icon=snap.joplin-james-carroll.joplin`, revert the layout change to snapcraft.yaml, and rename the `.svg` to `joplin.svg`, I'd pull this PR :)!

I'll need to push an extra commit after this since I've recently redone the build script to accomodate for some newer snap tech, but I'd be able to push a build to the candidate channel for you to test on your side in ~1-2 hours, and push this generally to stable for the 1.7 release

Thanks again for the work, good graphics design is something that requires a keen eye to detail and one I certainly don't have myself, so your contributions are appreciated :)

**Comment by elsiehupp** [comment]
Hi @MrCarroll~

The reason I went with `joplin-desktop` is that the "CFBundleIdentifier" Laurent uses on macOS is `net.cozic.joplin-desktop`. Since he doesn't actually seem to use `cozic.net` anymore, I made an additional alias called `org.joplinapp.joplin-desktop`. Incidentally, the bundle identifier for the iOS version appears to be `net.cozic.joplin` rather than `net.cozic.joplin-mobile`, so it's not strictly consistent.

If, though, despite the above, you think the identifier should be `snap.joplin-james-carroll.joplin` rather than `snap.joplin-james-carroll.joplin-desktop`, I trust your judgement, and I can use that for the `.desktop` file. (I can submit aliases for all of the different variations to `mint-y-icons`, though, just to be on the safe side.)

**Comment by JGCarroll** [comment]
Rethinking what I've said, my actual concern isn't entirely justified.

I was concerned that people would get confused how snap handles icon files (I.E, prior this commit, the name of the icon file itself was relevant because it has to match the alias in the manifest). The actual name of the file can still appear in `snap/gui` as is, it only matters what it's called to the systems perspective, which will be handled in the build script anyway. Long story short, it's not actually as confusing as I thought, I've just confused myself by accident :P.

I'd like the name of the .svg in `gui/` to be `joplin.svg` to help eliminate the snap specific confusion, but feel free actually to use `snap.joplin-james-carroll.joplin-desktop` for the Icon field.

**Comment by elsiehupp** [comment]
It appears that, yes, the SVG inside the snap is now called `joplin.svg`. And I added [a ton of aliases](https://github.com/linuxmint/mint-y-icons/pull/280/files) to my pull request over at `mint-y-icons`, though I don't know to what extent they're necessary. I will see how the maintainers respond!

**Comment by JGCarroll** [comment]
Since you've aliased both, I'll pull now and if the Mint devs are unhappy it can be changed in the future :)

I'll ping back here when there's a candidate build for you to test on

**Comment by elsiehupp** [comment]
By the way, if you'd like me to poke around at making GNOME/KDE-style and `mint-y`-style icons for your other snaps, that could be a fun task, too!

**Comment by JGCarroll** [comment]
I'd love to take you up on it but most my other snaps aren't as friendly with the authors as Joplin is, one I could think of that could potentially use your help and I know has a very receptive author is https://www.pinta-project.com/ 

The rest I think are in a legally dodgy area where I'd be afraid to change icons without their permission and I doubt I'd get permission for whatever reasons, the licenses might not stop us from doing it but I'd hate to be the "annoying snap guy who ruins our image and branding"

Anywhoo, I'll get to work on producing a build for you now :)

**Comment by elsiehupp** [comment]
Okay, cool! Perhaps with the other projects I could ask directly. In most cases the degree of intervention I would be suggesting is on par with the degree of intervention I had with the Joplin icons: basically I just GNOME-ified it.

It's worth mentioning that I do have [a pull request](https://github.com/laurent22/joplin/pull/4345) over at Laurent's repository, if you'd like to pop in and give feedback there. You could potentially also give some pointers on how [his `.desktop` file](https://github.com/laurent22/joplin/blob/de5bc45300ffe853667820fcca564182acd737b4/Joplin_install_and_update.sh#L180) could be adapted to work with icon themes like `mint-y`.

**Comment by JGCarroll** [comment]
Sure, I've popped some feedback over at the PR.

I think the desktop file being generated for the AppImage looks fine to me, it could be more explicit as you say with `joplin` vs `joplin-desktop`, but I think the majority of people don't consider the CLI as the "default" anyway. I don't think the upstream .desktop file would work any differently to the snap one based on what I know.

I've pushed a build with your changes to the candidate channel now, if the snap is already installed, `sudo snap refresh joplin-james-carroll --candidate`; this will download it and set your current installation to track the candidate channel, I'd probably suggest then `sudo snap switch --channel=stable joplin-james-carroll`, this won't take effect until the next stable update happens though, but it means you'll go back to downloading just the stable builds thereafter.

**Comment by elsiehupp** [comment]
Again, the only reason I used `joplin-desktop` specifically is that it's the bundle name in the Mac build's `Info.plist`. I mean, presuming Laurent ever used ["reverse DNS"](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s02.html) naming more consistently, I would expect the app IDs to match the package names in the repository, like so:

`org.joplinapp.app-cli`
`org.joplinapp.app-clipper`
`org.joplinapp.app-desktop`
`org.joplinapp.app-mobile`

or perhaps:

`org.joplinapp.joplin-cli`
`org.joplinapp.joplin-clipper`
`org.joplinapp.joplin-desktop`
`org.joplinapp.joplin-mobile`

I would leave that up to him, though.

**Comment by elsiehupp** [comment]
I tried installing the release candidate, and the icon within the snap is of course working, but I can't figure out how to test a theme-override icon. I copied the book icon into `~/.local/share/icons/hicolor/scalable`, as well as into the equivalent directory for the icon theme I'm currently using, but it doesn't seem to be doing anything. (I used the book icon because it's easily distinguishable from the button icon.)

**Comment by JGCarroll** [comment]
You'll need to make sure that you're the icon in a (sub?)folder with a higher priority than snap, `echo $XDG_DATA_DIRS` should tell you what the relative priorities are. I'm unsure when the desktop actually checks to update the icon it's using, the best I could suggest there is just log out and in again, I've never really done theming on Linux myself.

**Comment by elsiehupp** [comment]
It seems to be working now. I'm not sure what the precipitating factor was, though. Again, my main intention here is to make is so that the user on the Joplin forum can have their matching `mint-y-icon`-style Joplin icon. Personally I use a handful of non-standard icons, but for the most part I do stick with the GNOME defaults.

**Comment by JGCarroll** [comment]
Unfortunately I think I might have to revert the symbolic name for the time being.

Looking at the actual patch in snap that allows for symbolic names ( https://github.com/snapcore/snapd/pull/6767 ) it landed in snapd 2.42

Problematically, despite being released nearly one and a half years ago, Debian stable is still using 2.38 ( https://packages.debian.org/buster/snapd ), although there's a Debian specific system for updating snapd despite the native package, it doesn't fix the problem outside Debian distros, and even then few people do it from what I've seen.

Then there's other distributions like Solus, currently locked to 2.39 (https://dev.getsol.us/source/snapd/) which has absolutely no way of upgrading it until their maintainers do

Debian alone is a substantial amount of users, and they'd end up having no Joplin icon by default since their system would simply ignore the icon files in the snap.

On the balance of having themable icons and users having an icon at all, I have to prioritise the latter. In the future we can look into changing it again, but as is there's too many instances of snap held back in the wild.

The actual icon of course can stay :)

Sorry about the news, when I was testing I didn't think about these older distributions because frankly most people end up using Ubuntu and its derivatives where it isn't a problem, but there'll be more people broken by symbolic links for the time being than people who benefit from it.

**Comment by elsiehupp** [comment]
Oh, fun. FWIW, end users can still create their own `.desktop` files, and indeed "menu editor" applications create user-directory copies of read-only `.desktop` files when they get edited.

**Pull request merged**
