### PR TITLE
Themable icon

### PR DESCRIPTION
**Pull request by elsiehupp**
I remembered that the SVG version of the icon actually bakes one of the layer effects (the inner shadow on the "J" glyph), so over on the Joplin repository my pull request included a PSD version, which retains the editability. This doesn't make a difference for the actual rendered icon in the Linux shell, but it seems like a courtesy to the end user to include a properly editable source file for the icon.

### CODE REVIEW

**Comment by elsiehupp** [comment]
I also added a section to the `README.md` FAQ explaining how to manually enable icon theming.

**Comment by elsiehupp** [comment]
One thing I'm not 100% sure about is if manually copying `joplin.svg` to `~/.local/share/icons` as a backup with the custom `.desktop` file would preempt the icon from being themed.

I'm also not 100% sure if the workaround would actually work with older versions of `snapd`, though I imagine it should?

**Comment by JGCarroll** [comment]
I'm unsure about including the changes to the readme, whilst the problem is valid, snaps don't operate any differently here with how .desktop files themselves work. You can always in some method override or make new .desktop files and thus by extension the icon, problematically however, each individual desktop environment might have a lot of nuances in how to actually do this. I think it would be probably better to link to a blog post or some other documentation about icon themes and .desktop files instead. I remember in the Gnome 2 days you could just right click the menu entry and edit icons with zero fuss, and Gnome 2 is still in use with the MATE project, add on entirely other stacks like KDE, and tiling window manager families, and there's simply too much to consider IMO

Since Joplin does have issues with .desktop files in general in its AppImage format, it would make sense to document this in the upstream repo/website/forums instead and link to it from here, then snap just becomes an additional comment on the end of a generalised topic, rather than looking unique by itself, it'd also frankly be exposed to a much bigger audience to appreciate it, the visits to this repository directly are extremely few compared to the amount of people using the snap itself.

> I'm also not 100% sure if the workaround would actually work with older versions of snapd, though I imagine it should?

I don't believe older versions of snapd would be a problem.

**Comment by elsiehupp** [comment]
FWIW I tried renaming `joplin-james-carroll_joplin.desktop` to just `joplin.desktop`, and it stopped working, so the more complicated `Exec` string aside, the version of the `.desktop` file I put in the FAQ is specific to `joplin-snap`. Also, GUI `.desktop` editor applications like [MenuLibre](https://github.com/bluesabre/menulibre) don't present a straightforward way of using symbolic icon names.

As far as visibility goes, you could always expand the description on the Snapcraft page, but I don't know practical it would be to add the full FAQ. (I just checked, though, and the GNOME Software application does have selectable text.)

**Comment by elsiehupp** [comment]
> Since Joplin does have issues with .desktop files in general in its AppImage format, it would make sense to document this in the upstream repo/website/forums instead

I haven't tried using the AppImage version, so I'm not familiar with the issues there. From what I could see with the install script, though, [it does use a symbolic icon name](https://github.com/laurent22/joplin/blob/de5bc45300ffe853667820fcca564182acd737b4/Joplin_install_and_update.sh#L180).

**Comment by elsiehupp** [comment]
To be clear, someone should probably test the workaround on Debian or Solus regardless.

**Comment by JGCarroll** [comment]
I don't think the actual name of the .desktop file itself should matter, all that matters is it's contents. you should be able to rename them so I'm not sure why it didn't work.

The AppImage is awkard here, some distributions have functionality to install .desktop files for them automatically, Ubuntu certainly doesn't by default, I'm not sure the Joplin AppImage has the metadata to enable it even if it did. Instead, Joplin encourages (but doesn't force) users to run their installation script. Right off the bat, that's a lot of users who don't have .desktop files at all, AppImage encourages people to do things like simply put the file on the desktop and double click it to run.

For those who do, the symbolic icon their script uses is put in the users home directory, the FreeDesktop Standards don't actually even mention searching the folders its placed in so this is more undefined behaviour even if it generally works (The standards do mention $XDG_DATA_DIRS and on Ubuntu that folder isn't in it, but yet it still works for me), but it also means that the second the user installs Joplin with the official instructions, it will break the system icon theme for Joplin since the $HOME/.local folder will always have a higher priority in most systems.

I.E, if the user had ever run the AppImage installation script, the workaround for the snap icon won't work unless they manually clean up the AppImage install, simply deleting the Joplin binary and .desktop there isn't enough.

It's this kind of interplay that I think justifies treating this as a issue higher up, looking at the snap in situ doesn't answer the full scope of the problem, I do really it's better tackled at a higher level.

I've also picked up that the Exec= line mentions /snap/bin, in various distributions (Fedora, OpenSuse, and their derivatives), the /snap folder isn't even guaranteed to exist, which means these users would end up with an icon that loads nothing.

There's too many variables to make an easy to read FAQ here, if it's worth doing it's worth doing properly in a general format.

**Comment by elsiehupp** [comment]
That's fair enough. How do you like my simplified suggestion that people use something like [MenuLibre](https://github.com/bluesabre/menulibre)? I know you may be skeptical about including anything about icon theming in the FAQ, but at least this version of the advice offloads the problem onto someone else...

**Comment by JGCarroll** [comment]
Sure, I'm fine with that :)

It's not that I'm skeptical of including anything about icon theming by itself, the fact this ends up being a complex issue over what people would percieve as basic functionality is unfortunate and it's a failing on the Snap ecosystem this doesn't just work, but I'm skeptical of generally giving users enough information to possibly cause problems but not enough context to understand why. Saying to use MenuLibre is a much better option IMO because it puts the responsibility where it belongs, with people with a lot of understanding of the problem and a lot more documentation around it.

For example, I've had some knowledge about the corrupted font glyphs that I haven't updated into the FAQ for similar reasons, I could update it right now with some possible solutions but they're solutions with so many caveats amongst so much information in other places that I think the best since option is to wait until it's fixed properly, and it's annoying knowing that I'm doing that that but it's weighed on the balance of I'd rather people negatively reviewed the snap and said it didn't work and that the official/flatpak version is just better, than possibly encourage risk deleting their data by snooping around in places they might not properly understand.

I know to some degree it looks like I'm trying to ignore the problem and to a certain viewpoint that's true, I'd like for there to not be problems, but some problems are minor enough that helping people work around them might need consideration on how it's done, and often that's by being careful to not say too much.

**Comment by elsiehupp** [comment]
What is the expression... giving someone enough rope to hang themself? Yeah, you don't want to do that! 😬

**Pull request merged**
